# Generated by Django 3.1.1 on 2021-05-15 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_dttime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_dttime',
        ),
        migrations.AddField(
            model_name='event',
            name='attending_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
