# Generated by Django 3.1.1 on 2021-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210516_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_dttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_dttime',
            field=models.DateTimeField(),
        ),
    ]
