# Generated by Django 3.1.1 on 2021-05-20 17:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210520_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attending_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
