# Generated by Django 3.1.1 on 2021-05-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210520_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='host_id',
        ),
    ]
