# Generated by Django 3.1.1 on 2021-05-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=33)),
                ('reset_code', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(default='e536f0a390c6732ec127', editable=False, max_length=20)),
            ],
        ),
    ]
