# Generated by Django 3.1.1 on 2021-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='3726b5f3e65887ed310a', editable=False, max_length=20),
        ),
    ]
