# Generated by Django 3.1.1 on 2021-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210508_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='87ad88a93644580c8f13', editable=False, max_length=20),
        ),
    ]
