# Generated by Django 3.1.1 on 2021-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210512_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='f6681a943a332532ec53', editable=False, max_length=20),
        ),
    ]
