# Generated by Django 3.1.1 on 2021-05-15 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210512_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='e1e856affadef58394f5', editable=False, max_length=20),
        ),
    ]
