# Generated by Django 3.1.1 on 2021-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210520_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='2c2ed379f09fb72a76d2', editable=False, max_length=20),
        ),
    ]
